{% set name = "mergenotcombined" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/andvides/mergeNotCombined.git

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
